
services:
  app:
    image: ghcr.io/collinmurd/virtual-guillotine:latest
    ports:
      - "3001:3001"
    env_file:
      - /home/guillotine/.env
    volumes:
      - type: bind
        source: /home/guillotine/data
        target: /app/data
